# Note: Base output directory of /public is assumed for static files
default: &default
  manifest: manifest.json
  # /public/webpack
  webpack_public_output_dir: webpack

development:
  <<: *default
  # Default is localhost:3500
  hot_reloading_host: localhost:3500

  # Developer note: considering removing this option so it can ONLY be turned by using an ENV value.
  # Default is false, ENV 'HOT_RELOAD' will always override
  hot_reloading_enabled_by_default: false
